.TH SNSH 8 "29 Aug 2017" "version 1.0"
.SH NAME
SNSH - Simple Network Shell
.SH SYNOPSIS
.B <ipaddress>
.SH DESCRIPTION
.B SNSH
is a simple shell built for the network, I wrote this shell in my spare time.
Had nothing better to do and wanted to challenge myself in network programming.
There are a lot of builtin commands in Windows/Linux, there is a
.B term command in Linux that allows you to execute external shell commands.

." next paragraph
.PP
Note however that
.B SNSH - "(8) is still in early development, and may have a bug here or there."
If you have any problems with it, please feel free to email me and let me know.
.B Email: drunkenmaster1988@gmail.com
